version: '3.8'

services:

  frontend:
    image: employee-frontend
    ports:
      - "3000:80"

  backend:
    image: employee-backend
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    ports:
      - "27018:27017"